version: '3.8'

services:
  container-beer:
    container_name: container-beer
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.local
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./api.json:/api.json
    environment:
      SWAGGER_JSON: /api.json
  
volumes:
  data: