version: '3.8'

services:
  container-beer:
    container_name: container-beer
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.local
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./api_documentation.yaml:/api_documentation.yaml
    environment:
      SWAGGER_JSON: /api_documentation.yaml
  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor
    ports:
      - "8082:8080"
    volumes:
      - ./api_documentation.yaml:/api_documentation.yaml
    environment:
      SWAGGER_FILE: /api_documentation.yaml
  qodana:
    container_name: qodana-php
    image: jetbrains/qodana-php
    ports:
      - "8083:8080"
    volumes:
      - ./:/data/project/
    command:
      - --show-report

volumes:
  data: