version: '3.8'

services:
  container-beer:
    container_name: container-beer
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.local
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "8081:80"
    volumes:
      - data:/var/www/html
  
volumes:
  data: