framework:
    test: true
services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    App\BeerCatalog\Shared\Infrastructure\GuzzleHttpClientRepository:
        public: true
        
    BeerCatalog\Shared\Domain\HttpClientDataSource: ~
    BeerCatalog\Shared\Infrastructure\GuzzleHttpClientRepository: ~
#    App\BeerCatalog\Beer\Domain\DataSource\GetBeerDataSource: ~

    
    App\Tests\EndToEnd\:
        resource: '../tests/EndToEnd/*'